import { createFileRoute, Link, getRouteApi } from '@tanstack/react-router'
import { useQuery } from '@tanstack/react-query'
import { useEffect } from 'react'

const rootRouteApi = getRouteApi('__root__')
import { getPostFn, recordPostViewFn } from '@/server/actions/Database/services/post.service'
import { PostCard } from '@/components/feed/PostCard'
import { CommentItem, type CommentData } from '@/components/feed/CommentItem'
import { CommentComposer } from '@/components/feed/CommentComposer'
import type { Post } from '@/lib/entities/Post'
import { ArrowLeft } from 'lucide-react'
import { ogImageUrl, postUrl } from '@/lib/share/canonicalUrl'
import { buildShareDescription, buildShareTitle } from '@/lib/share/shareMeta'

export const Route = createFileRoute('/post/$postId')({
  loader: async ({ params, context }) => {
    // Session comes from root-route context (decrypted once per navigation).
    const post = await getPostFn({ data: { postId: params.postId } }).catch(() => null)
    return { session: context.session, post }
  },
  // What actually makes a shared link worth sharing. Without this the page
  // inherits the root's generic title and default image, so every post unfurled
  // identically — and blankly — on X, WhatsApp, Slack and Facebook.
  head: ({ loaderData, params }) => {
    // loaderData is genuinely optional in this context (preload passes, error
    // boundaries), not defensive padding.
    //
    // The cast is the same one the component body does below, for the same
    // reason: the Drizzle beta collapses nested relational results to a loose
    // union (see the note at server/queries.ts:68). Narrowing once here beats
    // repeating it at each of the three helper calls.
    const post = loaderData?.post as Post | null | undefined
    const url = postUrl(params.postId)

    if (!post) {
      return { meta: [{ title: 'Post not found · Closfa' }, { name: 'robots', content: 'noindex' }] }
    }

    const title = buildShareTitle(post)
    const description = buildShareDescription(post)
    const image = ogImageUrl(post)

    return {
      meta: [
        { title: `${title} · Closfa` },
        { name: 'description', content: description },
        { property: 'og:type', content: 'article' },
        { property: 'og:title', content: title },
        { property: 'og:description', content: description },
        { property: 'og:url', content: url },
        ...(image
          ? [
              { property: 'og:image', content: image },
              { property: 'og:image:width', content: '1200' },
              { property: 'og:image:height', content: '630' },
              { property: 'og:image:alt', content: description },
            ]
          : []),
        { name: 'twitter:card', content: image ? 'summary_large_image' : 'summary' },
        { name: 'twitter:title', content: title },
        { name: 'twitter:description', content: description },
        ...(image ? [{ name: 'twitter:image', content: image }] : []),
      ],
      // Two URLs address the same post (/post/:id and /?post=:id); this tells
      // crawlers which one is authoritative.
      links: [{ rel: 'canonical', href: url }],
    }
  },
  component: PostDetailPage,
})

function PostDetailPage() {
  const { session, post: initialPost } = Route.useLoaderData()
  const params = Route.useParams()

  // Same query key/shape as PostModal — posting a comment/reply just
  // invalidates ['post', postId] and both surfaces pick it up.
  const { data: post } = useQuery({
    queryKey: ['post', params.postId],
    queryFn: () => getPostFn({ data: { postId: params.postId } }),
    initialData: initialPost,
  })

  // Fire-and-forget — a view is a moment, not worth blocking render on or
  // retrying; one record per postId visited, not per re-render.
  useEffect(() => {
    recordPostViewFn({ data: { postId: params.postId } })

  }, [params.postId])

  // Deep-link from a comment/reply notification — scroll to and briefly
  // highlight the specific comment (reuses PostCard's own isFocused treatment
  // so the highlight class is already generated by Tailwind's content scan).
  const { commentId } = rootRouteApi.useSearch()
  useEffect(() => {
    if (!commentId || !post) return
    const el = document.getElementById(`comment-${commentId}`)
    if (!el) return
    el.scrollIntoView({ behavior: 'smooth', block: 'center' })
    el.classList.add('bg-accent-bg/40', 'rounded-lg')
    const timer = setTimeout(() => el.classList.remove('bg-accent-bg/40', 'rounded-lg'), 2500)
    return () => clearTimeout(timer)
  }, [commentId, post])

  return (
    <div className="min-h-screen bg-bg text-text">
      <main className="max-w-3xl mx-auto px-4 py-8 flex flex-col gap-8">
        <div className="flex items-center">
          <Link
            to="/"
            className="text-accent hover:text-accent-hover transition-all duration-[var(--motion-fast)] ease-[var(--motion-ease)] flex items-center gap-2 text-sm font-medium"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to feed
          </Link>
        </div>

        {post ? (
          <div className="flex flex-col gap-8">
            <PostCard post={post as unknown as Post}/>

            <div className="flex flex-col gap-6">
              <h3 className="text-text-h text-xl font-semibold">
                Comments ({post.comments})
              </h3>

              {session && (
                <CommentComposer postId={params.postId} currentUserName={session.name} />
              )}

              <div className="flex flex-col gap-4">
                {post.commentsList && post.commentsList.length > 0 ? (
                  (post.commentsList as unknown as CommentData[]).map((comment) => (
                    <CommentItem
                      key={comment.comment_id}
                      comment={comment}
                      currentUserId={session?.userId}
                      currentUserName={session?.name}
                    />
                  ))
                ) : (
                  <div className="text-text-s py-8 text-center italic opacity-80">
                    No comments yet. Be the first to start the conversation!
                  </div>
                )}
              </div>
            </div>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-20 text-center gap-2">
            <p className="text-text-h text-xl font-bold">Post not found</p>
            <p className="text-text-s max-w-xs">
              It may have been removed or the link is incorrect.
            </p>
          </div>
        )}
      </main>
    </div>
  )
}
